# Generated by Django 5.2 on 2025-06-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_orders_date_orders_modified_at_orders_summa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='summa',
            new_name='amount',
        ),
    ]
